version: "3.7"
services:
  redgold:
    user: root
    image: redgoldio/redgold:${REDGOLD_NETWORK:-dev}
    container_name: redgold-${REDGOLD_NETWORK:-dev}
    restart: unless-stopped
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    env_file:
      - ./var.env
    volumes:
      - ~/.rg:/root/.rg
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    command: ["--network", "${REDGOLD_NETWORK:-dev}", "node"]
    labels:
      - "com.centurylinklabs.watchtower.scope=redgold-${REDGOLD_NETWORK:-dev}"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-${REDGOLD_NETWORK:-dev}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120 --scope redgold-${REDGOLD_NETWORK:-dev} --cleanup
    labels:
      - "com.centurylinklabs.watchtower.scope=redgold-${REDGOLD_NETWORK:-dev}"
