services:
  wallet-rpc-testnet:
    container_name: ${CONTAINER_NAME:-monerotw}
    user: 1000:1000
    image: ghcr.io/sethforprivacy/simple-monero-wallet-rpc:latest
    volumes:
      - ${WALLET_DATA_DIR:-/disk/monerotw}:/home/monero/wallets
    restart: unless-stopped
    network_mode: "host"
    environment:
      - RPC_LOGIN=${RPC_LOGIN:-username:password}
      - DAEMON_HOST=${DAEMON_HOST:-http://127.0.0.1:28089}
    command:
      - --daemon-address=${DAEMON_HOST:-http://127.0.0.1:28089}
      - --rpc-bind-port=${WALLET_RPC_PORT:-28088}
      - --wallet-dir=/home/monero/wallets
      - --rpc-login=${RPC_LOGIN:-username:password}
      - --trusted-daemon
      - --disable-rpc-ban
      - --testnet