services:
  ethereum-node:
    image: ethereum/client-go
    container_name: ethereum
    restart: unless-stopped
    volumes:
      - /disk/ethereum:/root
    ports:
      - "8545:8545"
      - "30303:30303"
      - "8546:8546"  # WebSocket RPC port
      - "8551:8551"  # WebSocket RPC port
    command:
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3
      - --http.corsdomain=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --syncmode=snap
      - --db.engine=leveldb
      - --cache=1024
      - --maxpeers=50
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/root/jwt.hex
  beacon-chain:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    container_name: beacon-chain
    restart: unless-stopped
    volumes:
      - /disk/ethereum/beacon-chain:/beacon-data
      - /disk/ethereum/jwt.hex:/data/jwt.hex  # Add this line
    ports:
      - "4000:4000"
      - "13000:13000"
    command:
      - --accept-terms-of-use
      - --datadir=/beacon-data
      - --rpc-host=0.0.0.0
      - --grpc-gateway-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --execution-endpoint=http://ethereum-node:8551
      - --jwt-secret=/data/jwt.hex
      - --checkpoint-sync-url=https://mainnet-checkpoint-sync.attestant.io  # Add this line
      - --genesis-beacon-api-url=https://mainnet-checkpoint-sync.attestant.io  # Add this line