global:
  scrape_interval:     20s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'redgold'
    scrape_timeout: 10s
    scheme: 'http'
    params:
      format: [ 'prometheus' ]
    fallback_scrape_protocol: 'PrometheusText0.0.4'
    static_configs:
      - targets: ['localhost:16179']
        labels:
          environment: 'main'
      - targets: ['localhost:16279']
        labels:
          environment: 'test'
      - targets: ['localhost:16379']
        labels:
          environment: 'staging'
      - targets: ['localhost:16479']
        labels:
          environment: 'dev'
      - targets: ['localhost:16579']
        labels:
          environment: 'predev'
  - job_name: 'dynamic'
    scrape_timeout: 10s
    scheme: 'http'
    params:
      format: [ 'prometheus' ]
    fallback_scrape_protocol: 'PrometheusText0.0.4'
    scrape_interval: 1m
    file_sd_configs:
      - files:
          - targets.json
