[package]
name = "redgold-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "0.3.3"
serde = "1.0.163"

[lib]
crate_type = ["cdylib"]
