debug = false
priority = 32
#key = "189rjfadoisfj8923fjio"
mnemonic_words = "announce damage viable ticket engage curious yellow ten clock finish burden orient faculty rigid smile host offer affair suffer slogan mercy another switch park"