name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.CR_GPT_GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4
          PROMPT: "Please code review this pull request. The repository is written in rust and the project is focused on cryptocurrency."
          top_p: 1
          temperature: 1
  # It seems like this only works on public repos ? enable later
#  review2:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: feiskyer/ChatGPT-Reviewer@v0
#        name: ChatGPT Review 2
#        env:
#          GITHUB_TOKEN: ${{ secrets.CR_GPT_GITHUB_TOKEN }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          # OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
#        # Optional configurations:
#        with:
#          model: "gpt4"
#          temperature: 0.2
#          review_per_file: true
#          comment_per_file: true
