{
 "title": "Redgold",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": { "query": "label_values(environment)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Transactions Accepted Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redgold_transaction_accepted_total{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UTXO Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redgold_utxo_total{environment=~\"$env\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Observation Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redgold_observation_total{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "E2E Success 10m Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(redgold_e2e_success{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Accepted Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "rate(redgold_transaction_accepted{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exe Checksum",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "sum by(executable_checksum_last_8) (count by(executable_checksum_last_8) (redgold_node_executable_checksum_last_8{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}))\nand\nmax by(executable_checksum_last_8) (redgold_node_executable_checksum_last_8{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E Num Peer Observations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "redgold_e2e_num_peers{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Observations Received 10 Min Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "rate(redgold_observation_received{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Observation Height Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(redgold_observation_height{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "rate(redgold_peer_send{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Message Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(redgold_peer_message_received{environment=~\"$env\", job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}